export const lang = {
    en: {
        direction: 'ltr',
        userName: "userName",
        password: "password",
        send: "submit",
        logo: "MR/your name",
        errors: {
            addGrade: "add grade please !",
            goGradePage: "go to grade page...",
            connection: "connection confused",
            requireImg: "image only required",
            requrieVid: "video only requried",
            less15mg: "size must be less < 15 mg"
        },
        form: {
            gradeName: "grade name",
            lessonName: "lesson name",
            partName: "part name",
            unitName: "unit name",
            description: "description",
            degree: "degree",
            time: "time",
            question: "question",
            addQuestion: "add question",
            option: "option",
            removeQuestion: "remove question",
            rtOption: "right option",
            thumbnail: "thumbnail",
            video: "video",
            addLecture: "add lecture"

        },
        modal: {
            delete: "are you sure to delete?",
            confirm: "are you sure to send?",
            submit: "submit",
            cancel: "cancel",
            logOut: "are you sure to logout",

        },
        links: {
            exams: "exams",
            lectures: "lectures",
            usersInfo: "users info",
            users: "users",
            manageUsers: "mange users",
            management: "management",
            manageExams: "manage exams",
            manageLectures: "manage content",
            grades: "grades",
            logOut: "logout",
            addUser: "add user"
        },
        exams: {
            unit: "unit",
            lesson: "lesson",
            subtitle: "information about here",
            time: "time",
            nums: "nums",
            degree: "degree",
            start: "start",
            addExam: "add new exam",
            addUnitExam: "add unit exam",
            addLessonExam: "add lesson exam",
            removeExam: "exam",
            editExam: "edit exam",

        },
        users: {
            userName: "userName",
            password: "password",
            name: 'name',
            email: 'email',
            phone: "phone",
            familyPhone: "family phone",
            role: "role",
            action: 'action',
            grade: 'grade',
            showProfile: "show",
            isActive: "active",
            notActive: 'not active',
            settings: "settings",
            totalUsers: 'total users',
            addUser: "add user",
            chooseGrade: "choose grade",
            manage: "manage",
            activate: "activate",
            inActivate: "un activate",
            resetPassword: "reset Password",
            makeSubAdmin: "make SubAdmin",
            makeStudent: "make student",
            removeUser: "remove this User",
            noUserName: "no UserName found",
            onlyUserName: "only UserName is allowed for research",
        },
        content: {
            lectures: "lectures",
            units: "units",
            lecture: "lecture",
            unit: "unit",
            watch: "watch",
            lectureName: "lecture name",
            description: "description",
            editUnit: "editUnit",
            show: "show",
            addUnit: "add unit",
            addLesson: "add lesson",
            settings: "settings",
            lectureNums: "numbers of lecture",
            editLesson: "edit lesson name",
            addLecture: "add lecture",
            manageVids: "manage videos",
            editLecture: "edit lecture"
        }, grades: {
            gradeName: "grade name",
            addGrade: "add grade"
        }
    },
    ar: {
        direction: 'rtl',
        userName: "اسم المستخدم",
        password: "كلمة السر",
        send: "ارسال",
        search: "بحث",
        logo: " أ/اسم المنصه ",
        errors: {
            addGrade: "add grade please !",
            goGradePage: "go to grade page...",
            connection: "connection confused",
            requireImg: "مطلوب صوره",
            requireVid: "مطلوب فيديو",
            less15mg: "يجب ان يكون الملف اقل من 15 ميغا"
        },
        form: {
            gradeName: "السنه",
            lessonName: "الدرس",
            partName: "الجزء",
            unitName: "الوحده",
            description: "الوصف",
            degree: "الدرجه",
            time: "الوقت",
            question: "السؤال",
            addQuestion: "اضافه سؤال",
            option: "اختيار",
            removeQuestion: "ازاله سؤال",
            rtOption: "الاختيار الصحيح",
            thumbnail: "صوره الواجهه",
            video: "الفيديو",
            addLecture: "اضافه محاضره"
        },
        modal: {
            delete: "هل انت متاكد من الحذف ؟",
            confirm: "هل انت متاكد من ارسال البيانات ؟",
            submit: "ارسال",
            cancel: "اغلاق",
            logOut: "هل انت متاكد من تسجيل الخروج ؟",
        },
        links: {
            password: "كلمة المرور",
            exams: "الاختبارات",
            lectures: "المحاضرات",
            usersInfo: "اداره الطلاب",
            userProfile: "بيانات الطالب",
            users: "عرض الطلاب",
            manageUsers: "اداره الطلاب",
            management: "الاداره",
            manageExams: "اداره الاختبارات",
            manageLectures: "اداره المحتوى",
            grades: 'اداره السنوات',
            logOut: "تسجيل الخروج",
            addUser: 'اضافه طالب'
        },
        exams: {
            unit: "الوحدة",
            lesson: "الدرس",
            subtitle: "معلومات توضيحيه",
            time: "الوقت",
            nums: "عدد الاسئله",
            degree: "الدرجه",
            start: "ابدا الاختبار",
            addExam: "اضافه اختبار",
            addUnitExam: "اضافه وحده",
            addLessonExam: "اضافه درس",
            removeExam: "ازاله",
            editExam: "تعديل"
        },
        users: {
            userName: "اسم المستخدم",
            name: 'الاسم',
            email: 'البريد الالكترونى',
            phone: "الهاتف",
            familyPhone: "هاتف العائله",
            role: "الدور",
            password: "كلمة السر",
            grade: 'السنه',
            action: 'عرض',
            showProfile: "عرض ",
            isActive: "فعال",
            notActive: "غير فعال",
            settings: "الاعدادات",
            totalUsers: 'اجمالى الطلاب',
            addUser: "اضافه طالب",
            chooseGrade: "اختار السنه",
            manage: "الاداره",
            activate: "تفعيل",
            inActivate: "الغاء التفعيل",
            resetPassword: "ضبط كلمة السر",
            makeSubAdmin: "تعيين كمشرف",
            makeStudent: "الغاء الاشراف",
            removeUser: "ازالة المستخدم",
            noUserName: "لا يوجد هذا المستخدم",
            onlyUserName: "اسم المسنخدم فقط المسموح به للبحث",

        },
        content: {
            lectures: "المحاضرات",
            units: "الوحدات",
            lecture: "المحاضره",
            unit: "الوحده",
            watch: "مشاهده",
            lectureName: "اسم المحاضره",
            description: "الوصف",
            editUnit: "تعديل الاسم",
            show: "عرض",
            addUnit: "اضافه وحده",
            addLesson: "اضافه درس",
            settings: "الاعدادت",
            lectureNums: "عدد المحاضرات",
            editLesson: "تعديل اسم الدرس",
            addLecture: "اضافه محاضره",
            manageVids: "اداره المحاضرات",
            editLecture: "تعديل المحاضره"

        },
        grades: {
            gradeName: "اسم السنه ",
            addGrade: "اضافه سنه"
        }
    }
}